# Generated by Django 3.1.2 on 2020-11-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebTelefonos', '0002_marca_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='correo',
            field=models.EmailField(max_length=50),
        ),
    ]
